### ISSUE TITLE
DataSource updates not working for last deleted document in collection

### ISSUE THREAD

**Issue by mikhailmulyar** [1amageek/Ballcap-iOS#16]
### Describe the bug
When deleting last document in collection, DataSource not picking up changes and do not notify about removed items.
### [REQUIRED] Step 1: Describe your environment
  * Xcode version: 10.3  * Ballcap version: 0.10.4

### [REQUIRED] Step 3: Describe the problem
If last document in collection deleted snapshot is not processed. Issue caused by this line. https://github.com/1amageek/Ballcap-iOS/blob/cd943d1add107d477d56e5dbb8761b80f3dadb1c/Ballcap/DataSource.swift#L146
When deleting last document `lastSnapshot` is nil and `self._execute(snapshot: snapshot)` not getting called.

**Comment by KathiWinter** [comment]
After struggling with the same problem, this quick fix worked for me: 

`if let lastSnapshot = snapshot.documents.last {
                if !snapshot.metadata.hasPendingWrites {
                    self.query = self.query.start(afterDocument: lastSnapshot)
                }
            }`

The code doesn't return when the snapshot is empty and thus runs self._execute even on an empty snapshot.
I am not sure, what `self.query.start(afterDocument: lastSnapshot)` does and this code might have unwanted side effects.
Any ideas on this?  
I hope that this issue will officially be fixed in the near future.

**Comment by 1amageek** [comment]
@KathiWinter Thank you for message.
Fixed!
