### ISSUE TITLE
data optional

### ISSUE THREAD

**Issue by brightsider** [1amageek/Ballcap-iOS#9]
Why data is optional?

**Comment by 1amageek** [comment]
Ballcap's Document does not guarantee data retention. Ballcap's Document is similar to DocumentSnapshot.
DocumentReference and Data do not have to co-exist.

https://github.com/1amageek/Ballcap-iOS/blob/master/Ballcap/DataRepresentable.swift#L135

Ballcap's Document, initialized from DocumentSnapshot, returns a Document even if it does not hold data.Because DocumentSnapshot has SnapshotMetadata, which contains important information.
